<a href="https://colab.research.google.com/github/JoeHeeJae/Data-Analysising-Colon-coding/blob/main/%EB%B9%85%EB%8D%B0%EC%9D%B4%ED%84%B0_%EB%B6%84%EC%84%9D_%EC%8B%A4%EC%8A%B5_%EA%B3%B5%EA%B3%B5%EB%8D%B0%EC%9D%B4%ED%84%B0_%ED%99%9C%EC%9A%A9_%EC%A7%80%ED%95%98%EC%B2%A0%EC%9D%B4%EC%9A%A9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 라이브러리 import 하기

In [ ]:
import pandas as pd
import io

##파일 직접 업로드

In [ ]:
from google.colab import files
myfile = files.upload()

##csv 파일 불러오기

In [ ]:
station_people = pd.read_csv('서울시 지하철 호선별 역별 시간대별 승하차 인원 정보.csv', encoding='EUC-KR')
station_people.head()

FileNotFoundError: ignored

##Google Drive에서 파일 가져오기

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
filename = '/content/drive/MyDrive/서울시 지하철 호선별 역별 시간대별 승하차 인원 정보.csv'

In [ ]:
station_people = pd.read_csv(filename, encoding='EUC-KR')
station_people.head()

,사용월,호선명,지하철역,04시-05시 승차인원,04시-05시 하차인원,05시-06시 승차인원,05시-06시 하차인원,06시-07시 승차인원,06시-07시 하차인원,07시-08시 승차인원,...,23시-24시 하차인원,00시-01시 승차인원,00시-01시 하차인원,01시-02시 승차인원,01시-02시 하차인원,02시-03시 승차인원,02시-03시 하차인원,03시-04시 승차인원,03시-04시 하차인원,작업일자
0,202301,1호선,동대문,717,11,9399,1791,7814,5063,11183,...,7667,529,2104,5,254,0,0,0,0,20230203
1,202301,1호선,동묘앞,176,5,2429,929,3063,4244,5788,...,3400,80,1320,3,330,0,0,0,0,20230203
2,202301,1호선,서울역,555,27,6560,7430,11059,41800,36434,...,12316,3388,2777,69,235,0,5,0,0,20230203
3,202301,1호선,시청,95,0,2103,3753,3123,19320,6859,...,3160,353,703,1,22,0,0,0,0,20230203
4,202301,1호선,신설동,273,6,7568,1962,8198,6829,18129,...,7998,319,1941,3,28,1,0,0,0,20230203

In [ ]:
station_people.shape

(56951, 52)

##데이터 호출

In [ ]:
address = pd.read_csv(filename, encoding='EUC-KR')
# 호선명, 지하철 역 정보 추출
address = address.loc[address['사용월']==202301,:]
address = address[['호선명', '지하철역']]
address

     호선명 지하철역
0    1호선  동대문
1    1호선  동묘앞
2    1호선  서울역
3    1호선   시청
4    1호선  신설동
..   ...  ...
607  중앙선   원덕
608  중앙선   중랑
609  중앙선   지평
610  중앙선   팔당
611  중앙선   회기

[612 rows x 2 columns]

##정확한 위도와 경도를 얻기 위해 역 추가

In [ ]:
for i in address.index:
  station = ''.join(list(address.loc[i, ['지하철역']]))
  if station[-1] != '역':
    address.loc[i, ['지하철역']] = station + '역'

In [ ]:
!pip install googlemaps

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting googlemaps
  Downloading googlemaps-4.10.0.tar.gz (33 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: requests<3.0,>=2.20.0 in /usr/local/lib/python3.8/dist-packages (from googlemaps) (2.25.1)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages (from requests<3.0,>=2.20.0->googlemaps) (2022.12.7)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.8/dist-packages (from requests<3.0,>=2.20.0->googlemaps) (4.0.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests<3.0,>=2.20.0->googlemaps) (1.24.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests<3.0,>=2.20.0->googlemaps) (2.10)
Building wheels for collected packages: googlemaps
  Building wheel for googlemaps (setup.py) ... done
  Created wheel for googlemaps: filename=googlemaps-4.10.0-py3-none-any.whl size=40715 sha256=2fbe4b8f48e084c2061c114ffd62496e634fe3b4aee393405a4491cf754b6542
  Stored in directory: /root/.cache/pip/wheels/18/8a/74/69684f55a6b3e396f2b8e129f98b576cb02d6bebe66a0c3999
Successfully built googlemaps
Installing collected packages: googlemaps
Successfully installed googlemaps-4.10.0

In [ ]:
import googlemaps
from datetime import datetime

In [ ]:
my_key = "AIzaSyBKFplWkOv5ykWy_ZqhhyljcnOadmt8Ee4"
gmaps = googlemaps.Client(key = my_key)

In [ ]:
lat = [] #위도
lng = [] #경도

places = list(address['지하철역'])

tmap = gmaps.geocode('places', language="ko")

In [ ]:
i = 0
for place in places:
  i = i + 1
  try:
    geo_location = gmaps.geocode(place)[0].get('geometry')
    lat.append(geo_location['location']['lat'])
    lng.append(geo_location['location']['lng'])

  except:
    lat.append('')
    lng.append('')
    print("%d번 인덱스 위치를 찾는데 실패했습니다."%(i))


df = pd.DataFrame({'위도':lat, '경도':lng}, index=places)
df

1번 인덱스 위치를 찾는데 실패했습니다.
64번 인덱스 위치를 찾는데 실패했습니다.
99번 인덱스 위치를 찾는데 실패했습니다.
153번 인덱스 위치를 찾는데 실패했습니다.
200번 인덱스 위치를 찾는데 실패했습니다.
219번 인덱스 위치를 찾는데 실패했습니다.
278번 인덱스 위치를 찾는데 실패했습니다.
338번 인덱스 위치를 찾는데 실패했습니다.
566번 인덱스 위치를 찾는데 실패했습니다.

             위도          경도
동대문역
동묘앞역  37.573246  127.016589
서울역   37.555946  126.972317
시청역   37.565704  126.976862
신설동역  37.575326   127.02485
...         ...         ...
원덕역   37.468573   127.54716
중랑역   37.594904  127.075833
지평역   37.476496  127.629681
팔당역   37.547376  127.243813
회기역   37.589756  127.057977

[612 rows x 2 columns]

##이름 동일, 위도 경도 못찾은 역 삽입 처리

In [ ]:
address['위도'] = lat
address['경도'] = lng

# 동일한 역 처리
address.loc[(address['지하철역']=='동대문역')&(address['호선명']=='1호선'),"위도"]=37.571983
address.loc[(address['지하철역']=='동대문역')&(address['호선명']=='1호선'),"경도"]=127.011708

address.loc[(address['지하철역']=='동대문역')&(address['호선명']=='4호선'),"위도"]=37.571983
address.loc[(address['지하철역']=='동대문역')&(address['호선명']=='4호선'),"경도"]=127.011708

address.loc[(address['지하철역']=='고속터미널역')&(address['호선명']=='3호선'),"위도"]=37.5049142
address.loc[(address['지하철역']=='고속터미널역')&(address['호선명']=='3호선'),"경도"]=127.0049151

address.loc[(address['지하철역']=='고속터미널역')&(address['호선명']=='7호선'),"위도"]=37.5049142
address.loc[(address['지하철역']=='고속터미널역')&(address['호선명']=='7호선'),"경도"]=127.0049151

address.loc[(address['지하철역']=='고속터미널역')&(address['호선명']=='9호선'),"위도"]=37.5049142
address.loc[(address['지하철역']=='고속터미널역')&(address['호선명']=='9호선'),"경도"]=127.0049151

# 못찾는 역 삽입
address.loc[(address['지하철역']=='신정(은행정)역')&(address['호선명']=='5호선'),"위도"]=37.524765
address.loc[(address['지하철역']=='신정(은행정)역')&(address['호선명']=='5호선'),"경도"]=126.854275

address.loc[(address['지하철역']=='안암(고대병원앞)역')&(address['호선명']=='6호선'),"위도"]=37.586296
address.loc[(address['지하철역']=='안암(고대병원앞)역')&(address['호선명']=='6호선'),"경도"]=127.029137

address.loc[(address['지하철역']=='명학역')&(address['호선명']=='1호선'),"위도"]=37.3900837
address.loc[(address['지하철역']=='명학역')&(address['호선명']=='1호선'),"경도"]=126.9305068

address.loc[(address['지하철역']=='삼양역')&(address['호선명']=='우이신설'),"위도"]=37.626922
address.loc[(address['지하철역']=='삼양역')&(address['호선명']=='우이신설'),"경도"]=127.018164

address

     호선명  지하철역         위도          경도
0    1호선  동대문역  37.571983  127.011708
1    1호선  동묘앞역  37.573246  127.016589
2    1호선   서울역  37.555946  126.972317
3    1호선   시청역  37.565704  126.976862
4    1호선  신설동역  37.575326   127.02485
..   ...   ...        ...         ...
607  중앙선   원덕역  37.468573   127.54716
608  중앙선   중랑역  37.594904  127.075833
609  중앙선   지평역  37.476496  127.629681
610  중앙선   팔당역  37.547376  127.243813
611  중앙선   회기역  37.589756  127.057977

[612 rows x 4 columns]

address['위도'] = lat
address['경도'] = lng
M
# 동일한 역 처리
address.loc[(address['지하철역']=='동대문역')&(address['호선명']=='1호선'),"위도"]=37.571983
address.loc[(address['지하철역']=='동대문역')&(address['호선명']=='1호선'),"경도"]=127.011708

address.loc[(address['지하철역']=='동대문역')&(address['호선명']=='4호선'),"위도"]=37.571983
address.loc[(address['지하철역']=='동대문역')&(address['호선명']=='4호선'),"경도"]=127.011708

address.loc[(address['지하철역']=='고속터미널역')&(address['호선명']=='3호선'),"위도"]=37.5049142
address.loc[(address['지하철역']=='고속터미널역')&(address['호선명']=='3호선'),"경도"]=127.0049151

address.loc[(address['지하철역']=='고속터미널역')&(address['호선명']=='7호선'),"위도"]=37.5049142
address.loc[(address['지하철역']=='고속터미널역')&(address['호선명']=='7호선'),"경도"]=127.0049151

address.loc[(address['지하철역']=='고속터미널역')&(address['호선명']=='9호선'),"위도"]=37.5049142
address.loc[(address['지하철역']=='고속터미널역')&(address['호선명']=='9호선'),"경도"]=127.0049151

# 못찾는 역 삽입
address.loc[(address['지하철역']=='신정(은행정)역')&(address['호선명']=='5호선'),"위도"]=37.524765
address.loc[(address['지하철역']=='신정(은행정)역')&(address['호선명']=='5호선'),"경도"]=126.854275

address.loc[(address['지하철역']=='안암(고대병원앞)역')&(address['호선명']=='6호선'),"위도"]=37.586296
address.loc[(address['지하철역']=='안암(고대병원앞)역')&(address['호선명']=='6호선'),"경도"]=127.029137

address.loc[(address['지하철역']=='명학역')&(address['호선명']=='1호선'),"위도"]=37.3900837
address.loc[(address['지하철역']=='명학역')&(address['호선명']=='1호선'),"경도"]=126.9305068

address.loc[(address['지하철역']=='삼양역')&(address['호선명']=='우이신설'),"위도"]=37.626922
address.loc[(address['지하철역']=='삼양역')&(address['호선명']=='우이신설'),"경도"]=127.018164

address

In [ ]:
address.drop([0, 63],axis=0)

     호선명  지하철역         위도          경도
1    1호선  동묘앞역  37.573246  127.016589
2    1호선   서울역  37.555946  126.972317
3    1호선   시청역  37.565704  126.976862
4    1호선  신설동역  37.575326   127.02485
5    1호선  제기동역  37.578176  127.034591
..   ...   ...        ...         ...
607  중앙선   원덕역  37.468573   127.54716
608  중앙선   중랑역  37.594904  127.075833
609  중앙선   지평역  37.476496  127.629681
610  중앙선   팔당역  37.547376  127.243813
611  중앙선   회기역  37.589756  127.057977

[610 rows x 4 columns]

# 지도에 역 시각화 하기
<실패함>

In [ ]:
center = [37.541, 126.986]

import folium
from folium import Marker
c_dic = {'1호선':'darkblue','2호선':'green','3호선':'orange','4호선':'lightblue','5호선':'darkpurple','6호선':'black','7호선':'darkgreen','8호선':'pink','9호선':'beige','중앙선':'blue',
        '9호선2~3단계':'beige','경강선':'cadetblue','경부선':'cadetblue','경원선':'cadetblue','경의선':'cadetblue','경인선':'cadetblue','경춘선':'blue','공항철도 1호선':'cadetblue','과천선':'cadetblue','분당선':'lightred'
         ,'수인선':'lightred','안산선':'red','우이신설선':'cadetblue','일산선':'red','장항선':'cadetblue'}

In [ ]:

m = folium.Map(location=center, zoom_start=10)

In [ ]:
for i in range(len(address)):
  latitude = address['위도'][i]
  longitude = address['경도'][i]
  name = address['지하철역'][i]

marker = Marker([latitude, longitude], popup=name)
marker.add_to(m)
m

In [ ]:

# Choropleth 레이어를 만들고, 맵 m에 추가합니다.


marker = Marker([latitude, longitude], popup=name)
marker.add_to(m)

m.save('map.html')

m

# 데이처 전처리

In [ ]:
address.to_csv("서울교통공사_역주소_위경도.csv",index=False)

In [ ]:
for i in station_people.index:
  if int(station_people.loc[i,['사용월']])==202112:
    break

station_people = station_people.loc[:6041,:]
station_people.shape

(6042, 52)

In [ ]:
station_people.to_csv("서울시 지하철 호선별 역별 시간대별 승하차 인원 정보_202112까지.csv")

In [ ]:
# 데이터 load
station_people = pd.read_csv('서울시 지하철 호선별 역별 시간대별 승하차 인원 정보_202112까지.csv')

In [ ]:
# 승차 관련 컬럼만 필터링

in_subway=station_people.columns.tolist()[1:4]
for a in station_people.columns.tolist():
  if a.find('승차') != -1 :
    in_subway.append(a)

in_subway_df = station_people[in_subway]

in_subway_df.head()

,사용월,호선명,지하철역,04시-05시 승차인원,05시-06시 승차인원,06시-07시 승차인원,07시-08시 승차인원,08시-09시 승차인원,09시-10시 승차인원,10시-11시 승차인원,...,18시-19시 승차인원,19시-20시 승차인원,20시-21시 승차인원,21시-22시 승차인원,22시-23시 승차인원,23시-24시 승차인원,00시-01시 승차인원,01시-02시 승차인원,02시-03시 승차인원,03시-04시 승차인원
0,202301,1호선,동대문,717,9399,7814,11183,16599,15856,14762,...,22197,15214,12668,11599,8798,4311,529,5,0,0
1,202301,1호선,동묘앞,176,2429,3063,5788,9991,8011,8796,...,15881,7227,4744,4077,3044,1264,80,3,0,0
2,202301,1호선,서울역,555,6560,11059,36434,63029,52580,54340,...,199627,104878,75312,78469,51553,21933,3388,69,0,0
3,202301,1호선,시청,95,2103,3123,6859,8173,9615,12041,...,152460,56004,47529,44866,28432,9485,353,1,0,0
4,202301,1호선,신설동,273,7568,8198,18129,27315,17320,15380,...,47381,18433,12902,11208,7695,3532,319,3,1,0

In [ ]:
# 2022.04 ~ 2023.01 까지 합하여 승차가 제일 많은 곳
# 호선별

station_group=in_subway_df.drop(['사용월'], axis=1)

station_group

,호선명,지하철역,04시-05시 승차인원,05시-06시 승차인원,06시-07시 승차인원,07시-08시 승차인원,08시-09시 승차인원,09시-10시 승차인원,10시-11시 승차인원,11시-12시 승차인원,...,18시-19시 승차인원,19시-20시 승차인원,20시-21시 승차인원,21시-22시 승차인원,22시-23시 승차인원,23시-24시 승차인원,00시-01시 승차인원,01시-02시 승차인원,02시-03시 승차인원,03시-04시 승차인원
0,1호선,동대문,717,9399,7814,11183,16599,15856,14762,16202,...,22197,15214,12668,11599,8798,4311,529,5,0,0
1,1호선,동묘앞,176,2429,3063,5788,9991,8011,8796,13006,...,15881,7227,4744,4077,3044,1264,80,3,0,0
2,1호선,서울역,555,6560,11059,36434,63029,52580,54340,70370,...,199627,104878,75312,78469,51553,21933,3388,69,0,0
3,1호선,시청,95,2103,3123,6859,8173,9615,12041,17962,...,152460,56004,47529,44866,28432,9485,353,1,0,0
4,1호선,신설동,273,7568,8198,18129,27315,17320,15380,17539,...,47381,18433,12902,11208,7695,3532,319,3,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6037,분당선,서현,217,4157,12506,31281,39219,28199,25028,26269,...,81963,45323,43592,35771,26721,11743,452,0,0,0
6038,분당선,선릉,62,1059,2133,4601,6509,5477,6687,8343,...,75754,31643,19230,17965,16376,4631,196,0,0,0
6039,분당선,선정릉,7,874,1927,4577,6863,5880,5380,5934,...,44813,21161,10560,8812,6787,2040,42,0,0,0
6040,분당선,수내,80,2389,6646,17093,21944,14692,11928,13402,...,47463,24969,22979,15856,12980,3629,130,0,0,0
6041,분당선,수서,26,3294,5929,22928,36847,23436,21617,18209,...,39528,18183,18681,12624,13403,5043,13,0,0,0

In [ ]:
station_group2=station_group.groupby(['호선명', '지하철역']).sum()
station_group

NameError: ignored

#결과

In [ ]:
# 1호선
station_group2.loc['1호선'].style.background_gradient()

In [ ]:
center = [37.541, 126.986]

m = folium.Map(location=center, zoom_start=10)

HeatMap(data_list).add_to(m)

m.save('2020_08 이후 승차인원 포화상태.html')

m

SyntaxError: ignored